AWSTemplateFormatVersion: '2010-09-09'

Description: >
  AWS CloudFormation template for creating the S3 bucket that the web application uses.
  NOTE - This template should be run in region us-east-1 because the tenant-management web ui
  stack relies on the output, and it can only be run in us-east-1.

Parameters:
  WebUIOriginAccessIdentityId:
    Description: The ID of the OriginaAccessIdentity for the TAP UI
    Type: String

Resources:
  StaticTenantWebHostingS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: application-role
          Value: s3-bucket

  StaticTenantWebHostingS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticTenantWebHostingS3Bucket
      PolicyDocument:
        Statement:
          - Effect: 'Allow'
            Principal:
              AWS:
                - !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${WebUIOriginAccessIdentityId}
            Action:
              - 's3:GetObject'
            Resource:
              Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: 'StaticTenantWebHostingS3Bucket'
                  - '/*'

Outputs:
  S3BucketName:
    Value: !Ref StaticTenantWebHostingS3Bucket
    Description: The S3 bucket name
    Export:
      Name: !Sub ${AWS::StackName}-S3BucketName

  S3BucketSecureURL:
    Value: !Join ['', ['http://', !GetAtt [StaticTenantWebHostingS3Bucket, DomainName]]]
    Description: Name of S3 bucket that hosts the UI content
